### PR TITLE
PMAPI-1679: Add dedicated Campaigns API section

### PR DESCRIPTION
**Pull request by julielinter**
Fixes [PMAPI-1649](https://lobsters.atlassian.net/browse/PMAPI-1649)

## Checklist

- [x] Up to date with `main`
- [x] All the tests are passing
  - [ ] Delete all resources created in tests
- [ ] Prettier
- [x] Spectral Lint
- [x] `npm run bundle` outputs nothing suspect
- [x] `npm run postman` outputs nothing suspect

## Changes
* Adds a `Campaigns API (BETA)` section
* Moves campaigns-related endpoints to the dedicated Campaigns section

## Areas of Concern (optional)
Running `npm run pretty` makes changes to resources that I didn't touch. However, this causes the tests to fail 🤔 , so I abandoned those local changes.

### CODE REVIEW

**Comment by jho44** [comment]
@julielinter my bad on the "ready for review" tug-of-war. I thought I'd actually pressed something while looking through your PR. I just ran Prettier and you're right that it's fixing some things on `main`. But I don't see any tests failing on my end from the pre-commit hook. Do you know which resources are failing and why?

**Comment by BennyKitchell** [comment]
@julielinter  @jho44  I am still having to run `--no-verify` on  commit, so it's possible Julie also isn't configured correctly for it. So feel free to utilize that to get around the pre commit hooks.

**Review by BennyKitchell — APPROVED** [review]
LGTM!

**Comment by julielinter** [comment]
> @julielinter @jho44 I am still having to run `--no-verify` on commit, so it's possible Julie also isn't configured correctly for it. So feel free to utilize that to get around the pre commit hooks.

Yep, that was it - I forgot to run `--no-verify` on commit 🤦🏻‍♀️

**Pull request merged**
