### PR TITLE
feat(urlencoded): add urlencoded tests

### PR DESCRIPTION
**Pull request by jho44**
[ticket](https://lobsters.atlassian.net/jira/software/projects/DXP/boards/73?selectedIssue=DXP-174)

Aditi advised that I should just do one test for each group (PMAPI, billing, AV) rather than each resource. Chose checks_test, bank_accounts_test, and us_autocompletions_test.

Credit to [this post](https://github.com/OpenAPITools/openapi-generator/issues/7564) for helping me get URL encoding with deep Objects to work.

### CODE REVIEW

**Review by sudoku-lord — APPROVED** [review]

**Review by sudoku-lord — CHANGES_REQUESTED** [review]
Can you run `npx prettier -w <file name>` on these two files?

**Comment by jho44** [comment]
> Can you run `npx prettier -w <file name>` on these two files?
Done. Although I was also forced to (forced because I didn't know a way around it) add my .gitignore in in order to rebase off of main.

**Comment by sudoku-lord** [comment]
Ah, `bank_accounts_test.js` is Billing and `us_autocompletions_test.js` is AV. Could you add one into a PMAPI file? You can find the full list of PMAPI tests in `package.json` within the `goalieMappings` variable.

**Review by sudoku-lord — CHANGES_REQUESTED** [review]
See my comment re: PMAPI testing.

**Review by sudoku-lord — APPROVED** [review]

**Pull request merged**
